### ISSUE TITLE
DOC-3701: Test migration to official @asciidoctor/tabs extension

### ISSUE THREAD

**Issue by eric-schneider** [DataStaxDocs/datastax-streaming-docs-site#100]
/deploy-site playbook-ref="DOC-3701" npm-script="build:stage" deploy-server="coppi"

**Comment by eric-schneider** [comment]
/deploy-site playbook-ref="DOC-3701" npm-script="build:stage" deploy-server="coppi"

**Comment by eric-schneider** [comment]
/deploy-site playbook-ref="DOC-3701" npm-script="build:stage" deploy-server="coppi"

**Comment by mendonk** [comment]
/deploy-site playbook-ref="main" npm-script="build:stage" deploy-server="coppi"

**Comment by mendonk** [comment]
/deploy-site playbook-ref="main" npm-script="build:release" deploy-server="coppi"

**Comment by mendonk** [comment]
/deploy-site playbook-ref="main" npm-script="build:release" deploy-server="coppi" deploy-dir="en/streaming"

**Comment by mendonk** [comment]
/deploy-site playbook-ref="main" npm-script="build:release" deploy-server="preview"
