### ISSUE TITLE
Test stage builds

### ISSUE THREAD

**Issue by eric-schneider** [DataStaxDocs/datastax-streaming-docs-site#145]

**Comment by eric-schneider** [comment]
/deploy-site playbook-ref="main" npm-script="build:stage" deploy-server="coppi" deploy-dir="en/streaming"

**Comment by eric-schneider** [comment]
/deploy-site playbook-ref="test-luna-streaming-versions" npm-script="build:stage" deploy-server="coppi" deploy-dir="en/test-luna-streaming-versions"

**Comment by eric-schneider** [comment]
/deploy-site playbook-ref="test-luna-streaming-versions" npm-script="build:release" deploy-server="coppi" deploy-dir="en/test-luna-streaming-versions"

**Comment by eric-schneider** [comment]
/deploy-site playbook-ref="main" npm-script="build:release" deploy-server="coppi" deploy-dir="en/streaming"

**Comment by eric-schneider** [comment]
/deploy-site playbook-ref="stage" npm-script="build:stage" deploy-server="coppi" deploy-dir="en/streaming"

**Comment by eric-schneider** [comment]
/deploy-site playbook-ref="stage" npm-script="build:release" deploy-server="coppi" deploy-dir="en/streaming"

**Comment by eric-schneider** [comment]
/deploy-site playbook-ref="main" npm-script="build:stage" deploy-server="coppi" deploy-dir="en/streaming"

**Comment by eric-schneider** [comment]
/deploy-site playbook-ref="main" npm-script="build:release" deploy-server="coppi"

**Comment by eric-schneider** [comment]
/deploy-site playbook-ref="main" npm-script="build:stage" deploy-server="coppi"

**Comment by mendonk** [comment]
/deploy-site playbook-ref="main" npm-script="build:release" deploy-server="preview" deploy-dir="en/streaming"

**Comment by mendonk** [comment]
/deploy-site playbook-ref="main" deploy-server="production" npm-script="build:release"
