### ISSUE TITLE
Replace open graph meta tags with page specifics

### ISSUE THREAD

**Issue by ddieruf** [DataStaxDocs/datastax-streaming-docs-site#19]
Currently SEO optimizations included adding the og meta tag for image. This results in links showing a preview of a huge image which is not too helpful.

Follow a similar pattern to how GH issues work, where a shared link shows the title/part of desc of the page. This is helpful.

**Comment by mendonk** [comment]
/deploy-site playbook-ref=main deploy-server="preview" deploy-dir="en/streaming"
