### ISSUE TITLE
Testing a docsbot deploy

### ISSUE THREAD

**Issue by ddieruf** [DataStaxDocs/datastax-streaming-docs-site#21]

**Comment by ddieruf** [comment]
/deploy-site playbook-ref=main deploy-server="docs-preview" deploy-dir="en/streaming"

**Comment by ddieruf** [comment]
/deploy-site playbook-ref=main deploy-server="docs-preview" deploy-dir="en/streaming"

**Comment by ddieruf** [comment]
/deploy-site playbook-ref=main deploy-server="docs-preview" deploy-dir="en/streaming"

**Comment by mendonk** [comment]
/deploy-site playbook-ref=main deploy-server=preview deploy-dir="en/streaming"

**Comment by mendonk** [comment]
/deploy-site playbook-ref=main deploy-server="docs-preview" deploy-dir="en/streaming"

**Comment by mendonk** [comment]
/deploy-site playbook-ref=main deploy-server="coppi" deploy-dir="en/streaming"

**Comment by ddieruf** [comment]
/deploy-site playbook-ref=main deploy-server="preview" deploy-dir="en/streaming"

**Comment by ddieruf** [comment]
/deploy-site playbook-ref=main deploy-server="preview" deploy-dir="en/streaming"

Fixed missing files

**Comment by ddieruf** [comment]
/deploy-site playbook-ref=main deploy-server="preview" deploy-dir="en/streaming" debug=true

**Comment by ddieruf** [comment]
/deploy-site playbook-ref=main deploy-server="preview" deploy-dir="en/streaming" debug=true

**Comment by ddieruf** [comment]
/deploy-site playbook-ref=main deploy-server="preview" deploy-dir="en/streaming"

**Comment by ddieruf** [comment]
/deploy-site playbook-ref=main deploy-server="preview" deploy-dir="en/streaming" debug=true

**Comment by ddieruf** [comment]
/deploy-site playbook-ref=main deploy-server="preview" deploy-dir="en/streaming"

**Comment by ddieruf** [comment]
/deploy-site playbook-ref=main deploy-server="preview" deploy-dir="en/streaming"

**Comment by ddieruf** [comment]
/deploy-site playbook-ref=main deploy-server="preview" deploy-dir="en/streaming" debug=true

**Comment by ddieruf** [comment]
/deploy-site playbook-ref=main deploy-server="preview" deploy-dir="en/streaming" debug=true

Fixed debug logic, the VM should not be terminated.

**Comment by ddieruf** [comment]
/deploy-site playbook-ref=main deploy-server="preview" deploy-dir="en/streaming" debug=true

Added ssh-proxy to bsys keyscan list

**Comment by ddieruf** [comment]
/deploy-site playbook-ref=main deploy-server="coppi" deploy-dir="en/streaming" debug=true

**Comment by ddieruf** [comment]
/deploy-site playbook-ref=main deploy-server="preview" deploy-dir="en/streaming" debug=true

Added logic to allow some rsync warnings

**Comment by ddieruf** [comment]
/deploy-site playbook-ref=main deploy-server="preview" deploy-dir="en/streaming"

Trying to capture output correctly

**Comment by ddieruf** [comment]
/deploy-site playbook-ref=main deploy-server="preview" deploy-dir="en/streaming"

Only capture stderr

**Comment by ddieruf** [comment]
/deploy-site playbook-ref=main deploy-server="preview" deploy-dir="en/streaming"

Testing new messaging

**Comment by ddieruf** [comment]
/deploy-site playbook-ref=main deploy-server="preview" deploy-dir="en/streaming"

**Comment by mendonk** [comment]
/deploy-site playbook-ref=main deploy-server="coppi" deploy-dir="en/streaming"

**Comment by mendonk** [comment]
/deploy-site playbook-ref="stage" npm-script="build:stage" deploy-server="coppi"

**Comment by mendonk** [comment]
/deploy-site playbook-ref="spring" npm-script="build:stage" deploy-server="coppi"

**Comment by mendonk** [comment]
/deploy-site playbook-ref="stage" npm-script="build:stage" deploy-server="coppi"
