### ISSUE TITLE
Real-time data pipelines with Decodable

### ISSUE THREAD

**Issue by ddieruf** [DataStaxDocs/datastax-streaming-docs-site#26]
A guide to creating a web clicks  data processing pipeline with Decodable and Astra.

**Comment by ddieruf** [comment]
/deploy-site playbook-ref=real-time-data-pipelines-with-decodable

**Comment by ddieruf** [comment]
/deploy-site playbook-ref=real-time-data-pipelines-with-decodable

Forgot to set the learning site branch

**Comment by ddieruf** [comment]
/deploy-site playbook-ref=real-time-data-pipelines-with-decodable

Refinements.

**Comment by ddieruf** [comment]
@mendonk ready for your review

[https://coppi.aws.dsinternal.org/streaming-docs/real-time-data-pipelines-with-decodable/streaming-learning/use-cases-architectures/real-time-data-pipeline](https://coppi.aws.dsinternal.org/streaming-docs/real-time-data-pipelines-with-decodable/streaming-learning/use-cases-architectures/real-time-data-pipeline)

**Comment by mendonk** [comment]
/deploy-site playbook-ref=real-time-data-pipelines-with-decodable

@ddieruf review complete

**Comment by ddieruf** [comment]
/deploy-site playbook-ref=real-time-data-pipelines-with-decodable

**Comment by ddieruf** [comment]
/deploy-site playbook-ref=real-time-data-pipelines-with-decodable

**Comment by mendonk** [comment]
/deploy-site playbook-ref=real-time-data-pipelines-with-decodable

**Comment by mendonk** [comment]
/deploy-site playbook-ref=main deploy-server="preview" deploy-dir="en/streaming"

**Comment by mendonk** [comment]
/remove-site deploy-server=coppi deploy-dir="streaming-docs/real-time-data-pipelines-with-decodable"
