### ISSUE TITLE
Update logo in real time data pipeline image

### ISSUE THREAD

**Issue by ddieruf** [DataStaxDocs/datastax-streaming-docs-site#29]

**Comment by ddieruf** [comment]
/deploy-site playbook-ref=real-time-data-pipelines-with-decodable

**Comment by ddieruf** [comment]
@mendonk I've updated the architecture image

**Comment by mendonk** [comment]
/deploy-site playbook-ref=main deploy-server="preview" deploy-dir="en/streaming"
