### ISSUE TITLE
Onboarding (Enrollment) FAQ

### ISSUE THREAD

**Issue by ddieruf** [DataStaxDocs/datastax-streaming-docs-site#37]
Provide answers to frequently asked questions while onboarding in Astra Streaming.

**Comment by ddieruf** [comment]
@mendonk this is a winner. Please note the PR for DataStaxDocs/datastax-streaming-docs-site as well as astra-streaming-docs. I had to do a little stylesheet-fu.

**Comment by mendonk** [comment]
@ddieruf pushing some cleanup

**Comment by mendonk** [comment]
/deploy-site playbook-ref=main deploy-server="coppi" deploy-dir="en/streaming"

**Comment by mendonk** [comment]
/deploy-site playbook-ref=main deploy-server="preview" deploy-dir="en/streaming"

**Comment by mendonk** [comment]
/deploy-site playbook-ref=main deploy-server="preview" deploy-dir="en/streaming"
