### ISSUE TITLE
SEO Tweaks

### ISSUE THREAD

**Issue by ddieruf** [DataStaxDocs/datastax-streaming-docs-site#46]

**Comment by ddieruf** [comment]
/deploy-site playbook-ref="stage" npm-script="build:stage" deploy-server="coppi" deploy-dir="en/streaming"

**Comment by ddieruf** [comment]
@mendonk ready for you.
- Canonicals are the latest version of the product, even on old versions
- localhost doesn't automatically link
- Versioning is managed from the playbook not the component descriptor file
- Introduced a staging environment

Todo:
- Review rule for Pulsar-Docs "_" to "-"

**Comment by mendonk** [comment]
/deploy-site playbook-ref="main" npm-script="build:release" deploy-server="preview" deploy-dir="en/streaming"

**Comment by mendonk** [comment]
/deploy-site playbook-ref="stage" npm-script="build:stage" deploy-server="coppi" deploy-dir="en/streaming"

**Comment by mendonk** [comment]
/deploy-site playbook-ref="stage" npm-script="build:stage" deploy-server="coppi" deploy-dir="en/streaming"

**Comment by mendonk** [comment]
/deploy-site playbook-ref="stage" npm-script="build:stage" deploy-server="coppi" deploy-dir="en/streaming"

**Comment by mendonk** [comment]
/deploy-site playbook-ref="main" npm-script="build:release" deploy-server="preview" deploy-dir="en/streaming"

**Comment by ddieruf** [comment]
/deploy-site playbook-ref="main" deploy-server="production" npm-script="build:release"
