### ISSUE TITLE
Tell the CDC story

### ISSUE THREAD

**Issue by ddieruf** [DataStaxDocs/datastax-streaming-docs-site#51]
Currently, we have two areas focused on CDC:

[CDC for Cassandra](https://docs.datastax.com/en/cdc-for-cassandra/docs/2.2.2/index.html)
[CDC for Astra](https://docs.datastax.com/en/astra-serverless/docs/connect/astream-cdc.html)
[CDC for Astra (in streaming docs)](https://docs.datastax.com/en/streaming/astra-streaming/developing/astream-cdc.html)

Two of the three are guides. The CDC for C* is actual documentation. But it's a reference, leaving the reader to stitch together how to implement it.

Create a document(s) that tells the CDC story and provides examples in multiple runtimes.

What are the components/services involved?
How do they interact?
How do they scale?
What does a healthy CDC flow look like?
What are best practices?

**Comment by ddieruf** [comment]
/deploy-site playbook-ref="stage" npm-script="build:stage" deploy-server="coppi"

**Comment by ddieruf** [comment]
/deploy-site playbook-ref="stage" npm-script="build:stage" deploy-server="coppi"

**Comment by ddieruf** [comment]
/deploy-site playbook-ref="stage" npm-script="build:stage" deploy-server="coppi"

**Comment by ddieruf** [comment]
@mendonk this is ready to be merged and preview

**Comment by mendonk** [comment]
/deploy-site playbook-ref="main" npm-script="build:release" deploy-server="coppi"

**Comment by mendonk** [comment]
/deploy-site playbook-ref="main" npm-script="build:release" deploy-server="preview"

**Comment by mendonk** [comment]
/deploy-site playbook-ref="main" npm-script="build:release" deploy-server="coppi"

**Comment by mendonk** [comment]
/deploy-site playbook-ref="main" npm-script="build:release" deploy-server="coppi" deploy-dir="en/streaming"

**Comment by mendonk** [comment]
/deploy-site playbook-ref="main" npm-script="build:release" deploy-server="coppi" deploy-dir="en/streaming"

**Comment by mendonk** [comment]
/deploy-site playbook-ref="main" npm-script="build:release" deploy-server="preview" deploy-dir="en/streaming"

**Comment by mendonk** [comment]
/deploy-site playbook-ref="main" deploy-server="production" npm-script="build:release"
