### ISSUE TITLE
Cassandra enhanced sink clarifications

### ISSUE THREAD

**Issue by ddieruf** [DataStaxDocs/datastax-streaming-docs-site#63]
Add some more direction on how to consume the sink

**Comment by ddieruf** [comment]
/deploy-site playbook-ref="stage" npm-script="build:stage" deploy-server="coppi"

**Comment by ddieruf** [comment]
/deploy-site playbook-ref="stage" npm-script="build:stage" deploy-server="coppi"

**Comment by mendonk** [comment]
/deploy-site playbook-ref="main" npm-script="build:release" deploy-server="coppi" deploy-dir="en/streaming"

**Comment by mendonk** [comment]
/deploy-site playbook-ref="main" npm-script="build:release" deploy-server="preview" deploy-dir="en/streaming"

**Comment by mendonk** [comment]
/deploy-site playbook-ref="main" npm-script="build:release" deploy-server="preview" deploy-dir="en/streaming"

**Comment by mendonk** [comment]
/deploy-site playbook-ref="main" deploy-server="production" npm-script="build:release"
