### ISSUE TITLE
Operator crd reference

### ISSUE THREAD

**Issue by ddieruf** [DataStaxDocs/datastax-streaming-docs-site#75]
Building an api reference

**Comment by ddieruf** [comment]
/deploy-site playbook-ref="LS-944_crd-api-docs" npm-script="build:stage" deploy-server="coppi"

**Comment by ddieruf** [comment]
/deploy-site playbook-ref="LS-944_crd-api-docs" npm-script="build:stage" deploy-server="coppi"

**Comment by ddieruf** [comment]
/deploy-site playbook-ref="LS-944_crd-api-docs" npm-script="build:stage" deploy-server="coppi"

**Comment by mendonk** [comment]
Merged
