### ISSUE TITLE
AS-2484-automate-api-docs-generation

### ISSUE THREAD

**Issue by ddieruf** [DataStaxDocs/datastax-streaming-docs-site#78]
Generate api docs

**Comment by ddieruf** [comment]
/deploy-site playbook-ref="AS-2484-automate-api-docs-generation" npm-script="build:stage" deploy-server="coppi"

**Comment by ddieruf** [comment]
/deploy-site playbook-ref="stage" npm-script="build:stage" deploy-server="coppi"

**Comment by ddieruf** [comment]
/deploy-site playbook-ref="stage" npm-script="build:stage" deploy-server="coppi"

**Comment by ddieruf** [comment]
/deploy-site playbook-ref="stage" npm-script="build:stage" deploy-server="coppi"

**Comment by ddieruf** [comment]
/deploy-site playbook-ref="stage" npm-script="build:stage" deploy-server="coppi"

**Comment by ddieruf** [comment]
@mendonk this is ready

**Comment by mendonk** [comment]
/deploy-site playbook-ref="release" npm-script="build:release" deploy-server="coppi"

**Comment by mendonk** [comment]
/deploy-site playbook-ref="main" npm-script="build:release" deploy-server="coppi"

**Comment by mendonk** [comment]
/deploy-site playbook-ref="main" npm-script="build:release" deploy-server="coppi" deploy-dir="en/streaming"

**Comment by mendonk** [comment]
/deploy-site playbook-ref="main" npm-script="build:release" deploy-server="preview" deploy-dir="en/streaming"

**Comment by mendonk** [comment]
/deploy-site playbook-ref="main" deploy-server="production" npm-script="build:release"
