### ISSUE TITLE
Build operator for preview

### ISSUE THREAD

**Issue by mendonk** [DataStaxDocs/datastax-streaming-docs-site#83]

**Comment by mendonk** [comment]
/deploy-site playbook-ref="op" npm-script="build:stage" deploy-server="coppi" deploy-dir="en/streaming"

**Comment by mendonk** [comment]
/deploy-site playbook-ref="op" npm-script="build:stage" deploy-server="coppi"

**Comment by mendonk** [comment]
/deploy-site playbook-ref="op" npm-script="build:stage" deploy-server="coppi"

**Comment by mendonk** [comment]
/deploy-site playbook-ref="op" npm-script="build:stage" deploy-server="coppi"

**Comment by mendonk** [comment]
/deploy-site playbook-ref="op" npm-script="build:stage" deploy-server="coppi"

**Comment by mendonk** [comment]
/deploy-site playbook-ref="op" npm-script="build:stage" deploy-server="coppi" deploy-dir="en/streaming"

**Comment by mendonk** [comment]
/deploy-site playbook-ref="op" npm-script="build:stage" deploy-server="coppi"

**Comment by mendonk** [comment]
/deploy-site playbook-ref="op" npm-script="build:stage" deploy-server="coppi"

**Comment by mendonk** [comment]
/deploy-site playbook-ref="op" npm-script="build:release" deploy-server="coppi"

**Comment by mendonk** [comment]
/deploy-site playbook-ref="op" npm-script="build:release" deploy-server="coppi"

**Comment by mendonk** [comment]
/deploy-site playbook-ref="op" npm-script="build:release" deploy-server="coppi"

**Comment by mendonk** [comment]
/deploy-site playbook-ref="op" npm-script="build:stage" deploy-server="coppi"

**Comment by mendonk** [comment]
/deploy-site playbook-ref="operator-2" npm-script="build:stage" deploy-server="coppi"

**Comment by mendonk** [comment]
/deploy-site playbook-ref="operator-2" npm-script="build:stage" deploy-server="coppi"

**Comment by mendonk** [comment]
/deploy-site playbook-ref="op" npm-script="build:stage" deploy-server="coppi"

**Comment by mendonk** [comment]
/deploy-site playbook-ref="op" npm-script="build:stage" deploy-server="coppi"

**Comment by mendonk** [comment]
/deploy-site playbook-ref="op" npm-script="build:stage" deploy-server="coppi"

**Comment by mendonk** [comment]
/deploy-site playbook-ref="op" npm-script="build:stage" deploy-server="coppi"

**Comment by mendonk** [comment]
/deploy-site playbook-ref="op" npm-script="build:stage" deploy-server="coppi"

**Comment by mendonk** [comment]
/deploy-site playbook-ref="op" npm-script="build:stage" deploy-server="coppi"

**Comment by mendonk** [comment]
/deploy-site playbook-ref="op" npm-script="build:stage" deploy-server="coppi"

**Comment by mendonk** [comment]
/deploy-site playbook-ref="op" npm-script="build:stage" deploy-server="coppi"

**Comment by mendonk** [comment]
/deploy-site playbook-ref="op" npm-script="build:stage" deploy-server="coppi"

**Comment by mendonk** [comment]
/deploy-site playbook-ref="op" npm-script="build:stage" deploy-server="coppi"

**Comment by mendonk** [comment]
/deploy-site playbook-ref="op" npm-script="build:stage" deploy-server="coppi"

**Comment by mendonk** [comment]
/deploy-site playbook-ref="op" npm-script="build:stage" deploy-server="coppi"

**Comment by mendonk** [comment]
/deploy-site playbook-ref="op" npm-script="build:stage" deploy-server="coppi"

**Comment by mendonk** [comment]
/deploy-site playbook-ref="op" npm-script="build:stage" deploy-server="coppi"

**Comment by mendonk** [comment]
/deploy-site playbook-ref="op" npm-script="build:stage" deploy-server="coppi"

**Comment by mendonk** [comment]
/deploy-site playbook-ref="op" npm-script="build:stage" deploy-server="coppi"

**Comment by mendonk** [comment]
/deploy-site playbook-ref="op" npm-script="build:stage" deploy-server="coppi"

**Comment by mendonk** [comment]
/deploy-site playbook-ref="op" npm-script="build:stage" deploy-server="coppi"

**Comment by ddieruf** [comment]
/deploy-site playbook-ref="op" npm-script="build:stage" deploy-server="coppi"

**Comment by mendonk** [comment]
Now building with versioning, don't need main any more.
