### ISSUE TITLE
Created adverts for learning and Astra

### ISSUE THREAD

**Issue by ddieruf** [DataStaxDocs/datastax-streaming-docs-site#85]
Create 'em

**Comment by ddieruf** [comment]
/deploy-site playbook-ref="stage" npm-script="build:stage" deploy-server="coppi"

**Comment by mendonk** [comment]
/deploy-site playbook-ref="main" npm-script="build:release" deploy-server="preview" deploy-dir="en/streaming"

**Comment by mendonk** [comment]
/deploy-site playbook-ref="main" deploy-server="production" npm-script="build:release"
